<?php

namespace teamA\CrudBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ParentController__JMSInjector
{
    public static function inject($container) {
        $instance = new \teamA\CrudBundle\Controller\ParentController();
        return $instance;
    }
}
